#!/usr/bin/env bash
set -euo pipefail

GIT_USER=$(git config user.name)

if gh auth token -h github.com -u "$GIT_USER" > /dev/null 2>&1; then
  GH_TOKEN=$(gh auth token -h github.com -u "$GIT_USER")
  export GH_TOKEN
fi

if [[ "${GH_HOST:-}" != "github.com" ]]; then
  if gh auth token -u "$GIT_USER" > /dev/null 2>&1; then
    GH_ENTERPRISE_TOKEN=$(gh auth token -u "$GIT_USER")
    export GH_ENTERPRISE_TOKEN
  fi
fi

gh auth git-credential $*
